name: Run Bot

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "*/300 * * * *"

jobs:
  bot:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm

      - name: Install Dependencies
        run: npm install

      - name: Start Bot
        run: |
          timeout 5h npm start
